### ISSUE TITLE
FH weight argument

### ISSUE THREAD

**Issue by elong0527** [godwinyung/npsurvSS#1]
The `substring` function shall be `as.numeric(substring(weight[2], 2,2))`. Otherwise  `weight = "FH_[0]_[1]"` will not be able to calculate the weight properly. 

https://github.com/godwinyung/npsurvSS/blob/27af00c6dc1f1b03242f77c16e6f6abdc2d5398a/R/calc_central_moments.R#L64-L65

**Comment by godwinyyung** [comment]
Hi elong0527, weights should be specified as follows: "FH_p[a]_q[b]" where [a] and [b] are replaced by your desired FH parameters. For example, "FH_p0_q1" or "FH_p0.5_q0.5". The substring function will ignore the letters "p" and "q" and keep only the parameters [a] and [b].
